### ISSUE TITLE
Unused RFC reference warning when reference is in Appendix

### ISSUE THREAD

**Issue by danielmarschall** [ietf-tools/idnits#20]
Hello,

I am receiving following warning for my Internet Draft. [draft-viathinksoft-oidip-03](https://datatracker.ietf.org/doc/draft-viathinksoft-oidip/) :

**_Unused Reference: 'RFC8792' is defined on line 1056, but no explicit reference was found in the text_**

Example:
https://author-tools.ietf.org/api/idnits?url=https://www.ietf.org/archive/id/draft-viathinksoft-oidip-03.txt

But RFC8792 is used in the Appendix.

I have put the Appendix after the References section as recommended by many sources.

Did I do something wrong?

Kind regards,
Daniel Marschall

**Comment by danielmarschall** [comment]
Additional note:
In a previous version, I also tried to write

`# NOTE: '\' line wrapping per RFC 8792 [RFC8792]`

but this didn't work either.

**Comment by rjsparks** [comment]
Hi Daniel - you didn't do anything wrong. Please ignore the warning for now - it should not interfere with submission. A rewrite of idnits will make this different.
I'm going to close this issue. Please reopen it if you find I'm wrong and the warning does block submission.

**Comment by danielmarschall** [comment]
Hello Robert,
thank you for your reply.

I have found the reason why the reference was not detected.
It was because it was inside a `<CODE BEGINS>` block.
My assumption that the position in the Appendix was wrong.
After moving the reference out of the code block, it worked.

I wonder, should idnits look inside the code blocks to detect references or not? I think there are several pros and cons.
