### ISSUE TITLE
Idnits gives opposite suggestions

### ISSUE THREAD

**Issue by ju7ien** [ietf-tools/idnits#21]
### Describe the issue

A document I'm shepherding used to include in the abstract a phrase like "This document updates [RFCXXXX]" and Idnits requested to get rid of references there. The editors did the change, but now Idnits complaints (as a comment) that, considering the update field in the header, "the abstract doesn't seem to mention this, which it should".
To me, that I-D is fine to progress like this, but I'm not comfortable with that behavior of Idnits.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
References are not allowed in abstracts of RFCs at all, so removing the references was the right thing to do. The heuristics the current implementation of idnits uses to detect things like mentioning the updates can sometimes mis-guess. The issue here would be more useful if you provided a link to the draft where the heuristics missed.

In any case, we are working towards a replacement for idnits that will behave differently.

**Comment by ju7ien** [comment]
Hi Robert.  
Thanks for the feedback. The analysis that triggered my comment is here: https://author-tools.ietf.org/api/idnits?url=https://www.ietf.org/archive/id/draft-ietf-pce-local-protection-enforcement-07.txt

> In any case, we are working towards a replacement for idnits that will behave differently.

I saw that when filling in the shepherd write-up. If my comment is addressed as part of the rewriting, there's no reason to spend time tweaking the legacy implementation.

**Comment by rjsparks** [comment]
Ah - I see - the IESG _does_ want the Abstract to call out the Updates/Obsoletes information, but not as _references_.
When the document gets that far, they will ask for a sentence that looks like "This document updates RFC5540." But note that the RFC5540 string in the sentence is not a reference.

**Comment by ju7ien** [comment]
OK, that explains! So it isn't really a bug. I hope the future releases of Idnits will make that clearer, e.g. add "without square brackets" in the output.  
Thank you, Robert!
