### ISSUE TITLE
Idnits generates false positive for figures with Unicode characters

### ISSUE THREAD

**Issue by kszarkowicz** [ietf-tools/idnits#34]
I have draft that use Unicode characters in drawing (https://www.ietf.org/archive/id/draft-smn-idr-inter-domain-ibgp-03.txt). Running thus draft through https://author-tools.ietf.org/idnits results in 151 errors as follows:

"Line appears to be too long, but this could be caused by non-ascii characters in UTF-8 encoding"

Similar issue was opened in the past (issue #2574), which suppose to be fixed. However, false positive are still there.

**Comment by rjsparks** [comment]
The endpoint above is running the older idnits, not idnits3 which is under development.

**Comment by kszarkowicz** [comment]
OK. Sorry,

Let me close this issue, and open another issue for idnits2.

//Krzysztof

**Comment by kszarkowicz** [comment]
Closing this issue, and opening new issue for idnits2.
