### ISSUE TITLE
Please tag versions

### ISSUE THREAD

**Issue by samford** [ietf-tools/idnits#5]
Hi, I'm a maintainer for the [Homebrew package manager](https://brew.sh). We maintain an [`idnits` package](https://github.com/Homebrew/homebrew-core/blob/master/Formula/idnits.rb) but we don't have a way of checking for new versions at the moment. We used to check the tarball link on the [previous website](https://web.archive.org/web/20211111024543/https://tools.ietf.org/tools/idnits/) but the idnits page started redirecting to https://www6.ietf.org/tools/idnits/ around 2021-11 and the current website is only an online checker (no tarball link or version information).

I happened upon this repository and it seems like something we could migrate to in the future (now that it's no longer just a mirror) but we can't use it until there are version tags. Could you please create a tag for 2.17.00 (preferably pointing to the original commit, bfda9518d5b4e8a682f2e6f34a449c2d3ea745390)? Similarly, would you be willing to commit to tagging new versions as they're released? This would make it easy for us to download a snapshot of a given version and allow us to programmatically check the tags for new versions.

Somewhat related, are there any plans for releasing a new version? I see there are some new commits after 2.17.00 but the version in the `idnits` file remains the same.

Thanks!

**Comment by rjsparks** [comment]
We're not expecting this to be updated much at all in the future. The expectation is that it will be eclipsed by a different implementation. But hopefully these two tags/releases are helpful.
